project_id = "canopy-hub-sync"

[api]
enabled = true
port = 54321
schemas = ["public", "data", "raw", "storage", "graphql_public"]
extra_search_path = ["public", "data", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.data-sync]
verify_jwt = false

[functions.data-sync-dispatch]
verify_jwt = false
